# Generated by Django 3.0 on 2019-12-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='blog',
            name='body2',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='body3',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.TextField(default='', null=True),
        ),
    ]
